#!/bin/bash

# This shell script creates the documentation for qsb, modules and addons.

echo 'build QSB documentation'

# create folder
echo 'create destination directories'
rm -rf qsb/lua/var/build/doc &>/dev/null
rm -rf qsb/lua/var/md_doc &>/dev/null
mkdir -p qsb/lua/var/build/doc/temp/
mkdir -p qsb/lua/var/md_doc/

# create html documentation
cd qsb/exe/tools
cp docbuilderstart.txt ../../lua/var/build/doc/temp/docbuilder.lua
cp docbuilderend.txt ../../lua/var/build/doc/temp/docbuilderend.txt
cd ../../../

cd qsb/lua/modules
# Add modules to html documentation index
echo "Add modules to html documentation index"
for folder in *; do
    if ! ([ -f "$folder" ];) then
        cd $folder

        DESTINATION="../../var/build/doc/temp/docbuilder.lua"
        FILENAME="modules/${folder,,}.lua"
        if [ $folder = "QSB_0_Kernel" ]; then
            echo "" >> $DESTINATION
            FILENAME="qsb.lua"
        fi
        TITLE=$(head -n 1 title.txt)
        echo "{\"${FILENAME}\", \"${TITLE}\"}," >> $DESTINATION

        cd ../
    fi
done

# Add compatibility files to html documentation index
echo "Add compatibility files to html documentation index"
DESTINATION="../var/build/doc/temp/docbuilder.lua"
echo "{\"qsb_x_acomp.lua\", \"(X) Kompatibilität\"}," >> $DESTINATION
DESTINATION="../var/build/source/qsb_x_acomp.lua"
find . -maxdepth 2 -iname "compatibility.lua" -type f -exec cat {} +> $DESTINATION

cd ../../../

cd qsb/lua/addons
# Add addons to html documentation index
echo "Add addons to html documentation index"
for folder in *; do
    if ! ([ -f "$folder" ];) then
        cd $folder

        DESTINATION="../../var/build/doc/temp/docbuilder.lua"
        FILENAME="addons/${folder,,}.lua"
        if ! ([ $folder = "QSB_X_Addon_X_Template" ];) then
            TITLE=$(head -n 1 title.txt)
            echo "{\"${FILENAME}\", \"${TITLE}\"}," >> $DESTINATION
        fi

        cd ../
    fi
done
cd ../../../

# Finish creating docbuilder
echo "Finish creating docbuilder"
cd qsb/lua/var/build/doc/temp
cat "docbuilderend.txt" >> "docbuilder.lua"
cd ../../../../../../

#Temporary remove those files that need no documentation
cd qsb/lua/var
mv build/source/qsb_all.lua qsb_all.lua
mv build/source/qsb_comp.lua qsb_comp.lua
cd ../../../

# Builds the documentations of the single modules
echo "Build the documentations of the single modules"
cd qsb/exe/tools
lua ldoc/ldoc.lua -d ../../lua/var/build/doc -v ../../lua/var/build/source/ #&>/dev/null
cd ../../../

# Put back those files that need no documentation
cd qsb/lua/var
mv qsb_all.lua build/source/qsb_all.lua
mv qsb_comp.lua build/source/qsb_comp.lua

# Builds the documentation start page
echo "Build the documentations of the start page"
lua build/doc/temp/docbuilder.lua
cd ../../../

# Move html files into the build directory
rm -rf qsb/lua/var/build/doc/js
cp -r qsb/templates/js qsb/lua/var/build/doc
rm -rf qsb/lua/var/build/doc/css
cp -r qsb/templates/css qsb/lua/var/build/doc

# Create markdown documentation for qsb
echo "markdown-qsbbase"
lua qsb/exe/tools/ldoc/ldoc.lua --ext md -o "qsb/lua/var/md_doc/qsb.lua.md" -v "qsb/lua/var/build/source/qsb.lua" #&>/dev/null

# Create markdown documentation for modules
echo "markdown-modules"
cd qsb/lua/modules
for folder in *; do
    if ! ([ -f "$folder" ];) then
        cd $folder

        FILENAME="modules/${folder,,}.lua"
        if [ $folder = "QSB_0_Kernel" ]; then
            FILENAME="qsb.lua"
        fi
        lua ../../../exe/tools/ldoc/ldoc.lua --ext md -d "../../var/md_doc/${FILENAME}.md" "../../var/build/source/${FILENAME}" #&>/dev/null

        cd ../
    fi
done
cd ../../../

# Create markdown documentation for addons
cd qsb/lua/addons
for folder in *; do
    if ! ([ -f "$folder" ];) then
        cd $folder

        FILENAME="addons/${folder,,}.lua"
        if [ $folder = "QSB_X_Addon_X_Template" ]; then
            FILENAME="qsb.lua"
        fi
        lua ../../../exe/tools/ldoc/ldoc.lua --ext md -d "../../var/md_doc/${FILENAME}.md" "../var/../build/source/${FILENAME}" #&>/dev/null

        cd ../
    fi
done
cd ../../../

# Create markdown documentation for compatibility
lua qsb/exe/tools/ldoc/ldoc.lua --ext md -d "qsb/lua/var/md_doc/qsb_x_acomp.lua.md" "qsb/lua/var/build/source/qsb_x_acomp.lua" #&>/dev/null

# Remove temporary compatibility file
#rm qsb/lua/var/build/source/qsb_x_acomp.lua

# Remove temporary files
#rm -rf qsb/lua/var/build/doc/temp &>/dev/null

echo 'documentation ready'
