#!/bin/bash

# This shell script combines the source files into the qsb, the modules and the addons.
# The output is copied to qsb/lua/var/build

echo 'build QSB'

# create folder
echo 'create destination directories'
rm -rf qsb/lua/var &>/dev/null
mkdir -p qsb/lua/var/build/source/modules
mkdir -p qsb/lua/var/build/source/addons

# create core qsb and modules
cd qsb/lua/modules
for folder in *; do
    if ! ([ -f "$folder" ];) then
        cd $folder
        if [ $folder = "QSB_0_Kernel" ]; then
            # create core qsb
            echo "build qsb"
            DESTINATION="../../var/build/source/qsb.lua"
            find . -maxdepth 1 -iname "*.lua" -not -name "behavior.lua" -not -name "selfload.lua" -not -name "compatibility.lua" -type f -exec cat {} +> $DESTINATION
            cat "behavior.lua" >> $DESTINATION
            cat "selfload.lua" >> $DESTINATION
        else
            # create module
            echo "build module ${folder}"
            DESTINATION="../../var/build/source/modules/${folder,,}.lua"
            find . -maxdepth 1 -iname "*.lua" -not -name "compatibility.lua" -type f -exec cat {} +> $DESTINATION
        fi
        cd ../
    fi 
done

# create qsb with all modules
echo "build qsb_all"
DESTINATION="../var/build/source/qsb_all.lua"
find . -maxdepth 2 -iname "*.lua" -not -name "behavior.lua" -not -name "selfload.lua" -not -name "compatibility.lua" -type f -exec cat {} +> $DESTINATION
cat "QSB_0_Kernel/behavior.lua" >> $DESTINATION
cat "QSB_0_Kernel/selfload.lua" >> $DESTINATION

# create qsb with all modules and compatibility features
echo "build qsb_comp"
DESTINATION="../var/build/source/qsb_comp.lua"
find . -maxdepth 2 -iname "*.lua" -not -name "behavior.lua" -not -name "selfload.lua" -type f -exec cat {} +> $DESTINATION
cat "QSB_0_Kernel/behavior.lua" >> $DESTINATION
cat "QSB_0_Kernel/selfload.lua" >> $DESTINATION

# Create addons
cd ../addons
for folder in *; do
    if ! ([ -f "$folder" ];) then
        if ! ([ $folder = "Addon_X_Template" ];) then
            cd $folder
            echo "build addon ${folder}"
            cat *.lua > "../../var/build/source/addons/${folder,,}.lua"
            cd ../
        fi
    fi 
done

cd ../../../
echo "QSB ready"
