#!/bin/bash

# This shell script compiles the qsb files, the modules and the addons to improve load times.

echo 'compile QSB'

# create folder
echo 'create destination directories'
mkdir -p qsb/lua/var/build/bytecode/modules
mkdir -p qsb/lua/var/build/bytecode/addons

cd qsb/lua/var/minified

# compile qsb
echo 'compile QSB files'
luac -o ../build/bytecode/qsb.luac qsb_min.lua
luac -o ../build/bytecode/qsb_all.luac qsb_all_min.lua
luac -o ../build/bytecode/qsb_comp.luac qsb_comp_min.lua

# compile qsb modules
echo 'compile module files'
cd modules
for file in *.lua; do
    luac -o "../../build/bytecode/modules/${file/.lua/.luac}" "$file"
done
cd ../

# compile qsb addons
echo 'compile addon files'
cd addons
for file in *.lua; do
    luac -o "../../build/bytecode/addons/${file/.lua/.luac}" "$file"
done
cd ../

cd ../../../..

echo 'QSB compiled'