#!/bin/bash

# This shell script minifies the qsb files, the modules and the addons to use less disk space.
# temporary only copy to mimic minifying

echo 'minify QSB'

# create folder
echo 'create destination directories'
mkdir -p qsb/lua/var/minified/modules
mkdir -p qsb/lua/var/minified/addons

cd qsb/lua/var/build/source

# minify qsb
echo 'minify QSB files'
lua ../../exe/tools/luaminifier/CommandLineMinify.lua qsb.lua ../../minified/qsb.lua
lua ../../exe/tools/luaminifier/CommandLineMinify.lua qsb_all.lua ../../minified/qsb_all.lua
lua ../../exe/tools/luaminifier/CommandLineMinify.lua qsb_comp.lua ../../minified/qsb_comp.lua

# minify qsb modules
echo 'minify module files'
cd modules
for file in *.lua; do
    lua ../../../exe/tools/luaminifier/CommandLineMinify.lua "$file" "../../../minified/modules/${file}"
done
cd ../

# minify qsb addons
echo 'minify addon files'
cd addons
for file in *.lua; do
    lua ../../../exe/tools/luaminifier/CommandLineMinify.lua "$file" "../../../minified/addons/${file}"
done
cd ../

cd ../../../../..

echo 'QSB minified'