          #git config --global user.name 'Automatic Action'
          #git config --global user.email 'automaticAction@users.noreply.github.com'
          #git add -A
          #git commit -m "Automated Generation"
          #git push

on:
  workflow_dispatch:

jobs:
  buildJob:
    name: Creating QSB Release
    runs-on: ubuntu-latest
    steps:
    
      - name: checkout repo
        uses: actions/checkout@v2.7.0
        
      - name: Install Lua
        uses: leafo/gh-actions-lua@v10
        with:
         luaVersion: "5.1.1"
         
      - name: Install luaRocks
        uses: leafo/gh-actions-luarocks@v4.3.0
      
      - name: Install lua-Penlight
        run: luarocks install penlight
        
      - name: Install lua-htmlparser
        run: luarocks install htmlparser
      
      - name: Create Compiled LuaFiles
        run: bash qsb/exe/build_doc
                  
      - name: Push Result
        run: |
          git config --global user.name 'Automatic Action'
          git config --global user.email 'automaticAction@users.noreply.github.com'
          git add -A
          git commit -m "Automated Generation"
          git push

      - name: Upload Wiki Files
        run: |
          cd qsb/lua/var
          mkdir wiki_dir
          cd wiki_dir
          
          git init
          git config user.name 'Automatic Action'
          git config user.email 'automaticAction@users.noreply.github.com'
          git pull "https://${{ github.token }}@${GITHUB_SERVER_URL#https://}/$GITHUB_REPOSITORY.wiki.git"
          
          for file in $(find ../md_doc -maxdepth 1 -type f -name '*.md' -execdir basename '{}' ';'); do
              echo "Copying $file"
              cp "../md_doc/$file" "$file"
          done
          
          git add -A
          git commit -m "Automatically publish wiki"
          echo "Pushing"
          git push --set-upstream "https://${{ github.token }}@${GITHUB_SERVER_URL#https://}/$GITHUB_REPOSITORY.wiki.git" master
