on:
  workflow_dispatch:

jobs:
  my_job:
    name: test echo
    runs-on: ubuntu-18.04
    steps:
      - name: checkout repo
        uses: actions/checkout@v2.7.0
      - name: Change Directory and Print
        run: |
          pwd
          ls -a
          echo done with testing
          cd qsb/lua/tools
          ls -a
          pwd
          ls -a
