          #git config --global user.name 'Automatic Action'
          #git config --global user.email 'automaticAction@users.noreply.github.com'
          #git add -A
          #git commit -m "Automated Generation"
          #git push

on:
  workflow_dispatch:

jobs:
  buildJob:
    name: Creating QSB Release
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v2.7.0
      - name: Create QSB-Scripts
        run: |
          echo Building QSB
          bash qsb/exe/build_source
          echo QSB done
      - name: Make QSB-Zip for Release
        run: zip -r QSB_Release.zip qsb/lua/var/build
      - name: Get Tag of Branch
        #run: echo "{ReleaseTag}=$(git describe -tags)" >> $GITHUB_ENV
        run: echo "{ReleaseTag}={TestRelease}" >> $GITHUB_ENV
      - name: Git Release
        env:
         GH_TOKEN: ${{ github.token }}
        run: |
          gh release create ${{ env.ReleaseTag }} --latest --title "Test-Release" --notes "Test-Notes"
          gh release upload ${{ env.ReleaseTag }} QSB_Release.zip
