          #git config --global user.name 'Automatic Action'
          #git config --global user.email 'automaticAction@users.noreply.github.com'
          #git add -A
          #git commit -m "Automated Generation"
          #git push

on:
  workflow_dispatch:

jobs:
  buildJob:
    name: Creating QSB Release
    runs-on: ubuntu-latest
    steps:
    
      - name: checkout repo
        uses: actions/checkout@v2.7.0
        
      - name: Create QSB-Scripts
        run: |
          echo Building QSB
          bash qsb/exe/build_source
          echo QSB done
          
      - name: Install Lua
        uses: leafo/gh-actions-lua@v10
        with:
         luaVersion: "5.1.1"
      
      - name: Create Compiled LuaFiles
        run: |
         cd qsb/lua/var/build
         luac -o qsb.luac qsb.lua
         luac -o qsb_all.luac qsb_all.lua
         luac -o qsb_comp.luac qsb_comp.lua
         cd ../../../..
         
      - name: Make QSB-Zip for Release
        run: zip -rj QSB_Release.zip qsb/lua/var/build
        
      #- name: Get Tag of Branch
        #run: echo "{ReleaseTag}=$(git describe -tags)" >> $GITHUB_ENV
        #run: echo '{ReleaseTag}={v0.1-alpha}' >> $GITHUB_ENV
        
      - name: Git Release
        env:
         GH_TOKEN: ${{ github.token }}
         ReleaseTag: v0.1-alpha
        run: |
          gh release create $ReleaseTag --latest --title "Test-Release" --notes "Test-Notes"
          gh release upload $ReleaseTag QSB_Release.zip
