          #git config --global user.name 'Automatic Action'
          #git config --global user.email 'automaticAction@users.noreply.github.com'
          #git add -A
          #git commit -m "Automated Generation"
          #git push

on:
  workflow_dispatch:

jobs:
  buildJob:
    name: Creating QSB Release
    runs-on: ubuntu-latest
    steps:
    
      - name: checkout repo
        uses: actions/checkout@v2.7.0
        
      - name: Create QSB-Scripts
        run: bash qsb/exe/build_source
          
      - name: Install Lua
        uses: leafo/gh-actions-lua@v10
        with:
         luaVersion: "5.1.1"
      
      #TODO: build-doc einfuegen
      - name: Build Doc
        run: bash qsb/exe/build_doc
      
      - name: Minify Lua Files
        run: bash qsb/exe/minify_source
      
      - name: Create Compiled LuaFiles
        run: bash qsb/exe/compile_source
      
      #TODO: ZIP richtig anlegen und Dateien aus den Verzeichnissen nehmen
      #- name: Make QSB-Zip for Release
      #  run: zip -rj QSB_Release.zip qsb/lua/var/build
        
      - name: Git Release
        env:
         GH_TOKEN: ${{ github.token }}
         ReleaseTag: v0.1-alpha
        run: |
          gh release create $ReleaseTag --latest --title "Test-Release" --notes "Test-Notes"
          gh release upload $ReleaseTag QSB_Release.zip
