          #git config --global user.name 'Automatic Action'
          #git config --global user.email 'automaticAction@users.noreply.github.com'
          #git add -A
          #git commit -m "Automated Generation"
          #git push

on:
  workflow_dispatch:

jobs:
  buildJob:
    name: Creating QSB Release
    runs-on: ubuntu-20.040
    env:
     GH_TOKEN: ${{ github.token }}
    steps:
      - name: checkout repo
        uses: actions/checkout@v2.7.0
      - name: Create QSB-Scripts
        run: |
          echo Building QSB
          bash qsb/exe/build_source
          echo QSB done
      - name: Make QSB-Zip for Release
        run: zip -r QSB_Release.zip qsb/lua/var/build
      - name: Git Release
        run: gh release create --latest --title "Test-Release" --notes "Test-Notes" "QSB_Release.zip"
