          #git config --global user.name 'Automatic Action'
          #git config --global user.email 'automaticAction@users.noreply.github.com'
          #git add -A
          #git commit -m "Automated Generation"
          #git push

on:
  workflow_dispatch:

jobs:
  my_job:
    name: test echo
    runs-on: ubuntu-20.04
    steps:
      - name: checkout repo
        uses: actions/checkout@v2.7.0
      - name: Create QSB-Scripts
        run: |
          echo Building QSB
          bash qsb/exe/build_source
          echo QSB done
      - name: Make QSB-Zip for Release
        run: zip -r QSB_Release.zip qsb/lua/var/build
      - name: Git Release
        uses: anton-yurchenko/git-release@v5.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: QSB_Release.zip
          RELEASE_NAME: QSB-Release
