on:
  workflow_dispatch:

jobs:
  my_job:
    name: test echo
    runs-on: ubuntu-18.04
    steps:
      - name: pwd output
        run: pwd
      - name: ls output
        run: ls -a
      - name: Done Outputs
        run: echo done with testing
      - name: Trying Change Directory
        run: cd ..
      - name: pwd output
        run: pwd
      - name: ls output
        run: ls -a
